name: Test and Deploy

# Run this workflow whenever something new is pushed.
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  deploy:
    needs: run-tests # dependency
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "my_project/"
          target: "/home/cd/"

      # - name: ssh deploy
      #   uses: easingthemes/ssh-deploy@v2.1.6
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      #     REMOTE_HOST: ${{ secrets.SERVER_IP }}
      #     REMOTE_USER: ${{ secrets.DEPLOY_USER }}
      #     SOURCE: 'my_project/'
      #     TARGET: '/home/cd/'
