name: Test and Deploy

# Run this workflow whenever something new is pushed.
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  deploy:
    needs: run-tests
    runs-on: ubuntu-20.04
    steps:
      # - name: Install doctl
      #   uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.DIGITAL_OCEAN }}
      # - name: Copy folder to Digital Ocean
      #   uses: ./
      #   with:
      #     local: ./
      #     remote: scp/
      #   run: scp -i ~/.ssh/id_rsa.pub -r my-project root@134.209.198.158:/home/cd/
      #   with:
      #     token: ${{ secrets.DIGITAL_OCEAN }}
      # - name: restart NGINX
      #   uses: sh deploy.sh
      #   with:
      #     token: ${{ secrets.DIGITAL_OCEAN }}
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
      with:
        source: "."
        target: "/home/cd"
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: systemctl restart nginx