name: Test and Deploy

# Run this workflow whenever something new is pushed.
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  deploy:
    needs: run-tests # dependency
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.RSA_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.RSA_KEY }}
          source: "."
          target: "/home/cd/my-project"

      # - name: Copy file via scp
      #   uses: appleboy/scp-action@master
      #   env:
      #     HOST: ${{ secrets.SERVER_IP }}
      #     USERNAME: ${{ secrets.DEPLOY_USER }}
      #     PORT: ${{ secrets.DEPLOY_PORT }}
      #     KEY: ${{ secrets.DEPLOY_KEY_PV }}
      #   with:
      #     source: "."
      #     target: "/home/cd" 

      # - name: Executing remote  command
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     USERNAME: ${{ secrets.USERNAME }}
      #     PORT: ${{ secrets.PORT }}
      #     KEY: ${{ secrets.SSHKEY }}
      #     script: cat /opt/app/README.md


# systemctl restart cd.service